### ISSUE TITLE
Use *.in suffix for inputs to e2ls.1 and tests/simple-test.sh

### ISSUE THREAD

**Issue by christophgysin** [e2tools/e2tools#17]
Currently we have files with ending `.1in` and `.shin`. Add an extra dot to have them end with `.in`

It's been a while since I have actively used autotools, but isn't there a way to process `.in` files directly without manually passing them through sed?

**Comment by ndim** [comment]
My first priority was to get this working reliably.

The make rule must not be a pattern rule like `%.1: %.1.in` due to compatibility with non-GNU make. So the make rule must be a suffix rule with which I am not as familiar, and for suffix rules this was the quickest way to get this to work reliably.

Post e2tools-0.1 release, I can do some experiments with suffix rules and the `SUFFIXES` variable to reliably build `foo.ext` from `foo.ext.in`. This does not affect any users, does it?

As to why I use the `SED` rule inside the `Makefile.am` instead of declaring the files in the parameters to `AC_CONFIG_FILES` in `configure.ac`, this is the best practise to reliably regenerate the files when needed.

**Comment by christophgysin** [comment]
Ok, lets postpone this for now.
